version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Skipping tests"
      - npm run build --if-present
artifacts:
  files:
    - '**/*'
